# Generated by Django 5.2.4 on 2025-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
